---
 - hosts: all
   ignore_errors: yes
   become: yes
   tasks:
     
     - name: install tree
       yum:
         name: tree
         state: present
       when: ansible_distribution == "CentoS"


     - name: install tree
       apt:
         name: tree
         state: present
       when: ansible_distribution == "Ubuntu"
